version: '3.8'

services:
  # 1. DATABASE (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: kyntus-db
    restart: always
    environment:
      POSTGRES_DB: kyntus_db
      POSTGRES_USER: kyntus_user
      POSTGRES_PASSWORD: kyntus_password
    ports:
      - "5432:5432"
    volumes:
      # Volume v2 li 7ell lina mochkil permissions
      - postgres_data_v2:/var/lib/postgresql/data

  # 2. BACKEND (Spring Boot)
  backend:
    build: ./Workflow
    container_name: kyntus-backend
    restart: always
    ports:
      # Port 8080 ldakhel, 8082 bra (Host)
      - "8082:8080"
    depends_on:
      - db
    environment:
      # Config DB Dynamique
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kyntus_db
      - SPRING_DATASOURCE_USERNAME=kyntus_user
      - SPRING_DATASOURCE_PASSWORD=kyntus_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # 3. FRONTEND (Next.js)
  frontend:
    build:
      context: ./frontend
      # ðŸ”¥ FIX MOHIM: Kan-passiw l-URL wa9t l-Build bach Next.js y-fhemnou
      args:
        NEXT_PUBLIC_API_URL: http://kyntusos.kyntus.fr:8082
    container_name: kyntus-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Runtime variable (Ziyada f l-khir)
      - NEXT_PUBLIC_API_URL=http://kyntusos.kyntus.fr:8082

volumes:
  postgres_data_v2: