version: '3.8'

services:
  # 1. DATABASE (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: kyntus-db
    restart: always
    environment:
      POSTGRES_DB: kyntus_db
      POSTGRES_USER: kyntus_user
      POSTGRES_PASSWORD: kyntus_password
    ports:
      - "5432:5432"
    volumes:
      # Volume v2 bach nt-fadaou machakil permissions l-9dam
      - postgres_data_v2:/var/lib/postgresql/data

  # 2. BACKEND (Spring Boot)
  backend:
    build: ./Workflow
    container_name: kyntus-backend
    restart: always
    ports:
      # L-Backend dima ghadi n-pointiw 3lih b 8082 f Server
      - "8082:8080"
    depends_on:
      - db
    environment:
      # Config DB Dynamique bach tkhdem m3a l-container 'db'
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kyntus_db
      - SPRING_DATASOURCE_USERNAME=kyntus_user
      - SPRING_DATASOURCE_PASSWORD=kyntus_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # 3. FRONTEND (Next.js)
  frontend:
    build:
      context: ./frontend
      # ðŸ”¥ HNA FIN KAY-T-7EL L-MOCHKIL:
      # Kan-siftou l-URL l-Dockerfile wa9t l-Build bach ma-yb9ach "localhost"
      args:
        NEXT_PUBLIC_API_URL: http://kyntusos.kyntus.fr:8082
    container_name: kyntus-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Variable d l'environnement f l-runtime (Safety net)
      - NEXT_PUBLIC_API_URL=http://kyntusos.kyntus.fr:8082

volumes:
  # L-volume l-jdid dyalna
  postgres_data_v2: