version: '3.8'

services:
  # 1. DATABASE (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: kyntus-db
    restart: always
    environment:
      POSTGRES_DB: kyntus_db
      POSTGRES_USER: kyntus_user
      POSTGRES_PASSWORD: kyntus_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. BACKEND (Spring Boot)
  backend:
    build: ./Workflow
    container_name: kyntus-backend
    restart: always
    ports:
      # ðŸ”¥ FIX IMPORTANT: Bra (Host) = 8082 | Ldakhel (Container) = 8080
      # Hakka kantfadaw l-mochkil m3a 'apples_backend' li chad 8080
      - "8082:8080"
    depends_on:
      - db
    environment:
      # Hna kan-injectiw les variables bach application.properties yfhemhom
      # 'db' hna hiya smiyet l-service li lfou9 ðŸ‘†
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kyntus_db
      - SPRING_DATASOURCE_USERNAME=kyntus_user
      - SPRING_DATASOURCE_PASSWORD=kyntus_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # 3. FRONTEND (Next.js)
  frontend:
    build: ./frontend
    container_name: kyntus-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Frontend khasso ya3ref fin ja Backend (Machi localhost, walakin Host IP/Domain)
      # Pour l'instant on laisse localhost cotÃ© client browser
      - NEXT_PUBLIC_API_URL=http://kyntusos.kyntus.fr:8082

volumes:
  postgres_data: